### ISSUE TITLE
Geo Settings and mobile friendly versions

### ISSUE THREAD

**Issue by sudhan77** [collective/collective.geo.bundle#33]
In the Geo Settings , the Georeferenceable content types and Default Map layers options are not pre-populated. What should be done.

Also is there any options to make this adapt to mobile by identifying the device type

**Comment by sudhan77** [comment]
this maynot be an issue with collective.geo, but i am not gtting options with georeferenceable content types and default map layers and balloon details. please suggest what i could try to resolve this

**Comment by pbauer** [comment]
@sudhan77 Pinn z3c.form to 4.3.4. There was a bug with the orderedselect-widget.
Please always provide which versions of Plone and collective.geo you are using. 
The mobile thing is a feature-request. Please open a different ticket for that (maybe with a little more detail).

**Comment by sudhan77** [comment]
thanks. resolved. pls pinn z3c.form to 3.3.4

On Sat, Sep 5, 2015 at 1:57 PM, Philip Bauer notifications@github.com
wrote:

> @sudhan77 https://github.com/sudhan77 Pinn z3c.form to 4.3.4. There was
> a bug with the orderedselect-widget.
> Please always provide which versions of Plone and collective.geo you are
> using.
> The mobile thing is a feature-request. Please open a different ticket for
> that (maybe with a little more detail).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/collective/collective.geo.bundle/issues/33#issuecomment-137928811
> .

## 

Sudhanshu
